import "./globals.css";

import { barlow } from "./fonts";

export const metadata = {
  title: "Space Tourism Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.className}>{children}</body>
    </html>
  );
}
